/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as timelockControllerUpgradeableSol from "./TimelockControllerUpgradeable.sol";
export type { timelockControllerUpgradeableSol };
export type { NektakGovernorUpgradeable } from "./NektakGovernorUpgradeable";
export type { NektakTokenUpgradeable } from "./NektakTokenUpgradeable";
